# Generated by Django 3.2.11 on 2022-02-17 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='actualization',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=True)),
                ('license_plate', models.CharField(max_length=7, unique=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='accounts.producer')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='producer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('gta', models.IntegerField()),
                ('cargo', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadings', to='accounts.truck')),
            ],
            options={
                'verbose_name': 'Loading',
                'verbose_name_plural': 'Loading',
                'ordering': ['-publication'],
            },
        ),
    ]
