# Generated by Django 3.2.11 on 2022-02-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220217_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='status',
            field=models.CharField(choices=[('Loading', 'Loading'), ('Finished', 'Finished')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loadings', to='accounts.truck'),
        ),
    ]
