# Generated by Django 3.2.11 on 2022-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220218_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
